# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20170511_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='addr',
        ),
    ]
